services:
  db:
    image: mysql:8.0
    container_name: mysql_erudio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: belmira74
      MYSQL_DATABASE: rest_with_springboot_erudio
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rest_with_springboot_erudio?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: belmira74
    volumes:
      - ./UploadDir:/estudos/UploadDir

volumes:
  mysql_data: