server:
  port: 80
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.erudio.com.br
file:
  upload-dir: /estudos/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
email:
  subject: "Default Subject"
  message: "Default Message"
spring:
  application:
    name: rest-with-spring-boot-and-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/rest_with_springboot_erudio?useTimezone=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:belmira74}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  flyway:
    enabled: true
    baseline-on-migrate: false
    clean-disabled: true
    locations: classpath:db/migration
    out-of-order: true

logging:
  level:
    root: INFO
    # net.sf.jasperreports.engine.*: TRACE
    br.com.swetonyancelmo: DEBUG
    org.flywaydb.core: DEBUG
    org.hibernate: DEBUG

spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true